# Generated by Django 3.1.2 on 2020-10-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_replies'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default='', null=True)),
                ('reply_id', models.IntegerField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'likesreply',
            },
        ),
    ]
