# Generated by Django 3.1.2 on 2020-10-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_likesreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='posts',
            name='public',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
