# Generated by Django 3.1.2 on 2020-11-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201101_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='LikesComment',
        ),
        migrations.DeleteModel(
            name='LikesReply',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='PostAttach',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='Replies',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
