# Generated by Django 3.1.2 on 2020-11-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201106_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('subject', models.CharField(default='', max_length=250, null=True)),
                ('body', models.CharField(default='', max_length=250, null=True)),
                ('read', models.CharField(default='0', max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
