# Generated by Django 3.1.2 on 2020-11-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='condition',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
