# Generated by Django 3.1.2 on 2020-11-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=250)),
                ('description', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(default='')),
                ('jobtype', models.CharField(default='', max_length=250)),
                ('remote', models.CharField(default='', max_length=250)),
                ('salary', models.CharField(default='', max_length=250)),
                ('travle', models.CharField(default='', max_length=250)),
                ('client', models.CharField(default='', max_length=250)),
                ('benefits', models.TextField(default='', max_length=1000)),
                ('worauth', models.TextField(default='', max_length=1000)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
