# Generated by Django 3.1.2 on 2020-11-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='email',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='jobs',
            name='lat',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='jobs',
            name='lng',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='jobs',
            name='phone',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='jobs',
            name='reply',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='jobs',
            name='url',
            field=models.CharField(default='', max_length=250),
        ),
    ]
