# Generated by Django 3.1.2 on 2020-11-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201109_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='travle',
            new_name='travel',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='worauth',
            new_name='workauth',
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_zip',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
