# Generated by Django 3.1.2 on 2020-11-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowsPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_id', models.IntegerField(default='')),
                ('user_id', models.IntegerField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'followspage',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default='')),
                ('title', models.CharField(default='0', max_length=250, null=True)),
                ('avatar', models.ImageField(default='', null=True, upload_to='page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'page',
            },
        ),
        migrations.CreateModel(
            name='PageToUserInvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_id', models.IntegerField(default='')),
                ('user_id', models.IntegerField(default='')),
                ('status', models.CharField(default='0', max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pagetouserinvite',
            },
        ),
    ]
