# Generated by Django 3.1.2 on 2020-11-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.IntegerField(default='', null=True)),
                ('user_id', models.IntegerField(default='', null=True)),
                ('content', models.TextField(default='', max_length=1000, null=True)),
                ('read', models.CharField(default='0', max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('who', models.IntegerField(default='', null=True)),
                ('whom', models.IntegerField(default='', null=True)),
                ('accepted', models.CharField(default='0', max_length=1, null=True)),
                ('status', models.CharField(default='', max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
