# Generated by Django 3.1.2 on 2020-11-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='visibleto',
            field=models.CharField(default='1', max_length=1, null=True),
        ),
    ]
