# Generated by Django 3.1.2 on 2020-11-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_posts_page_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GifImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gifimg', models.FileField(default='', null=True, upload_to='gif')),
                ('gifimgname', models.TextField(default='', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gifimg',
            },
        ),
    ]
