# Generated by Django 3.1.2 on 2020-11-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default='')),
                ('title', models.CharField(default='0', max_length=250, null=True)),
                ('avatar', models.ImageField(default='', null=True, upload_to='group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='GroupToUserInvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(default='')),
                ('user_id', models.IntegerField(default='')),
                ('status', models.CharField(default='0', max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grouptouserinvite',
            },
        ),
    ]
