# Generated by Django 3.1.2 on 2020-11-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_followsgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(default='')),
                ('user_id', models.IntegerField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'likegroup',
            },
        ),
    ]
