# Generated by Django 3.1.2 on 2020-11-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_likegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default='', null=True)),
                ('group_id', models.IntegerField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'viewsgroup',
            },
        ),
    ]
